dist: trusty

language: node_js
node_js:
  - "8"
  - node

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

before_install:
  - npm i -g yarn codecov

install:
  - yarn install --frozen-lockfile

script:
  - yarn test && codecov

jobs:
  include:
    - stage: Release
      if: branch = master AND type = push
      node_js: node
      script: yarn semantic-release
